import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cls } from "./libs/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  title?: string;
  hasTabBar?: boolean;
  canGoBack?: boolean;
  children: React.ReactNode;
}

export default function RootLayout({
  children,
  title,
  hasTabBar,
  canGoBack,
}: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white w-full text-xl font-semibold py-6 fixed text-gray-700 border-0 top-0 left-0 flex items-center justify-center">
          {title ? <span>{title}</span> : null}
        </div>
        <div className={cls("pt-16", hasTabBar ? "pb-16" : "")}>{children}</div>
        {hasTabBar ? (
          <nav className="bg-white text-gray-800 border-t fixed bottom-0 pb-10 pt-3 flex justify-between items-center"></nav>
        ) : null}
      </body>
    </html>
  );
}
